### ISSUE TITLE
My project tries to link to tuneup_js

### ISSUE THREAD

**Issue by JBarberU** [vkolgi/tuneup_js#77]
I'm building an iOS app and the only pod I'm currently using is tuneup_js and the problem I'm facing is that my project tries to link against the Pods-library, which can't be built as there is no Objective C code in there. 

I guess this might be an issue with cocoapods rather than tuneup itself, but as cocoapods is the recommended way of installing it this might be worth resolving. 

My solution was to simply not link against the Pods-library for the time being.

Please let me know if I submit this this issue to cocoapods instead. And thanks for a neat library.

**Comment by vkolgi** [comment]
Closing the issue as .rb and .js files are referenced as resources in podspec file as per this commit
https://github.com/vkolgi/tuneup_js/pull/80/commits/63f241c025c8f033b6479117c09411fba5b7fba4
