### ISSUE TITLE
Test start-up time has worsened in 1.2.3 release

### ISSUE THREAD

**Issue by dueckes** [vkolgi/tuneup_js#84]
The addition of the following line has significantly slowed the start-up time of my tests (imposing a 20 second pause):
https://github.com/alexvollmer/tuneup_js/blob/master/uiautomation-ext.js#L5

I may be missing something - is there some way to restore normal performance (configuration change or otherwise)?

**Comment by vkolgi** [comment]
This issues is fixed by configuring 1 sec timeout for finding a non existent element.
Merge Info here.
https://github.com/vkolgi/tuneup_js/commit/456fedeb1114b1159b4353b0858ee6ffab90fe59
